// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzdwtcazjqkftmesyccl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZHd0Y2F6anFrZnRtZXN5Y2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTU5NDYsImV4cCI6MjA2Njc5MTk0Nn0.Su_fDHzyER5O7HRIOEuaHiK6HmMSPrVaz20XF1US0iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);